#!/bin/sh

export DISPLAY=:99

XVFB_WHD=${XVFB_WHD:-1280x720x16}

_kill_procs() {
  kill -TERM $chromium
  wait $chromium
  kill -TERM $xvfb
  wait $xvfb
  kill -TERM $dbus
  rm -f /var/run/dbus.pid
}

# Start dbus-daemon
[ ! -e /var/run/dbus ] && mkdir /var/run/dbus
/usr/bin/dbus-daemon --system
dbus=$(pgrep dbus-daemon)

# Setup a trap to catch SIGTERM and relay it to child processes
trap _kill_procs SIGTERM

# Start Xvfb
Xvfb ${DISPLAY} -ac +iglx -screen 0 $XVFB_WHD -nolisten tcp & xvfb=$!

# Start Chromium
/usr/lib/chromium/chrome --no-sandbox $@ &
chromium=$!

wait $chromium
wait $xvfb
